### ISSUE TITLE
filetype is not detected when the dictionary header contains the string “C++” in it

### ISSUE THREAD

**Issue by reverseila** [lervag/vim-foam#3] opened 2021-12-21 05:17 UTC
Most of the OpenFOAM dictionary files have a header that contains C++ in them. As a result, in my case, neovim thinks that's a cpp buffer. Am I missing something?

It's a little annoyance, particularly when one uses LSP. I don't know if it's my config or a problem with neovim or the plugin.

**Comment by lervag** [comment] 2021-12-21 07:39
Can you give an example of the header of such a file? (I.e. top 15 lines, or less.)

**Comment by reverseila** [comment] 2021-12-21 14:15
The one without the `C++` string in it, which is perfectly detected as a `foam` file type:

```
// ************************************************************************* //

FoamFile
{
    version 2.0;
    format  ascii;
    class   dictionary;
    object  funckySetFieldsDict;
}

// ************************************************************************ //
```

And here is the one that is detected as a C++ file:

```
/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  8
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      controlDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
```

For the above case, if I use a modeline to set the filetype, it will detect it as a `foam` file.

**Comment by lervag** [comment] 2021-12-21 21:16
Thanks. The problem is that the first line contains "C++", which is matched by the autodetection scheme in `$VIMRUNTIME/filetype.vim` through `$VIMRUNTIME/scripts.vim`. So, a simple fix would be to change the initial comment line and remove the "C++" part. Not quite sure how to fix this in a good way, to be honest.

**Comment by reverseila** [comment] 2021-12-22 08:37
Yes exactly.  Anyway, I'm using the following shell script:

```sh
#!/bin/sh

# Fail on error
set -e

# Only run this in a root of a case
! [ -d "0" -a -d "constant" -a -d "system" ] \
    && printf "You are not in a case. Usage: `basename $0` [-f]\n" && exit 1

# Remove C++ from header
for file in `\grep -l -R 'C++'`
do
    if [ "$1" = "-f" ]; then # Actually change it
        cp "$file" "${file}.orig"
        sed -E 's#(/\*.*)[[:space:]]C\+\+[[:space:]](.*\*\\)#\1-----\2#g' \
            "${file}.orig" > "$file"
        rm "${file}.orig"
    else # Dry run
        echo
        echo "-- $file --"
        echo "before:"
        cat "$file" | head -n 1
        echo "after:"
        sed -E 's#(/\*.*)[[:space:]]C\+\+[[:space:]](.*\*\\)#\1-----\2#g' \
            "$file" \
            | head -n 1
    fi
done
```

**Comment by lervag** [comment] 2021-12-22 10:08
Thanks for the info and suggested script for "fixing" it. And yes, I think we should close the issue - I don't have any good ideas for fixing this in a more reliable manner. Sorry. :\

**Closed by lervag** 2021-12-22 10:08 UTC
